# Inserisci qui i dati delle tue API
# Sono richiesti solo i permessi 'View' e 'Trade'

API_KEY = 'API_KEY_HERE'
API_SECRET = 'API_SECRET_HERE'
API_PASSPHRASE = 'API_PASSPHRASE_HERE'

SANDBOX_API_KEY = 'API_KEY_HERE'
SANDBOX_API_SECRET = 'API_SECRET_HERE'
SANDBOX_API_PASSPHRASE = 'API_PASSPHRASE_HERE'
